spring.application.name=learningSpringBoot
spring.datasource.url=jdbc:mysql://localhost:3307/studentdb
spring.datasource.username=root
spring.datasource.password=mant1234@MMJ

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true